// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChr3ym7N1up8lA5JFeAwPbggcWIkM9cRg',
    appId: '1:1067497462234:android:7e3bfb2dec5bec1ca2c8e3',
    messagingSenderId: '1067497462234',
    projectId: 'fathers-prophets',
    databaseURL: 'https://fathers-prophets-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fathers-prophets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU7_oxca1gDuSjgRQSSV5vBw36jkBzyTE',
    appId: '1:1067497462234:ios:eecf4c4595695013a2c8e3',
    messagingSenderId: '1067497462234',
    projectId: 'fathers-prophets',
    databaseURL: 'https://fathers-prophets-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fathers-prophets.firebasestorage.app',
    iosBundleId: 'com.fathersprophets.fathersProphets',
  );
}
